### ISSUE TITLE
How to find the ./mini_nvs_solver-0.1.0-py3-none-any.whl file

### ISSUE THREAD

**Issue by Yujie-G** [pablovela5620/mini-nvs-solver#1]
thx for your nice work.
I run `pixi run app` and found that  `ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory xxx/mini_nvs_solver-0.1.0-py3-none-any.whl`
Is there something I missing?

**Comment by pablovela5620** [comment]
Could you try `pixi run python tools/gradio_app.py`, I think it may be trying to run the hf_spaces version and first running https://github.com/pablovela5620/mini-nvs-solver/blob/fd1ed8ca8de601bed4c1c7106a9b39907348e662/pyproject.toml#L33C1-L34C1

**Comment by Yujie-G** [comment]
I changed my network env and now it's been solved. However, the sigma_list in https://github.com/pablovela5620/mini-nvs-solver/blob/fd1ed8ca8de601bed4c1c7106a9b39907348e662/mini_nvs_solver/sigma_utils.py#L14 seems to be ignored by the git. Would you mind upload it?

**Comment by Yujie-G** [comment]
I solved it using new network env. Thanks for your help
